spring:
  datasource:
    url: jdbc:mysql://localhost:3300/mydb?createDatabaseIfNotExist=true
    username: root
    password: Jipnp-112@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect











